package com.xindaibao.cashloan.cl.sdk.bairong.model;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Created by xiezhao on 2017/10/21.
 */
@Getter
@Setter
@NoArgsConstructor
public class BaiRongRradeRespDTO {

    private Integer brcreditpoint;
    private String code;
    private String swift_number;
    private String sl_lm_cell_nbank_ca_refuse;
    private String sl_lm_cell_nbank_com_fraud;
    private String sl_lm_cell_nbank_ca_bad;
    private String sl_lm_cell_bank_overdue;
    private String sl_lm_cell_nbank_other_refuse;
    private String sl_lm_cell_nbank_mc_fraud;
    private String sl_lm_cell_nbank_mc_lost;
    private String sl_lm_cell_nbank_other_bad;
    private String sl_lm_cell_nbank_mc_overdue;
    private String sl_lm_cell_nbank_com_refuse;
    private String sl_lm_cell_nbank_ca_overdue;
    private String sl_lm_cell_nbank_p2p_bad;
    private String sl_lm_cell_nbank_other_overdue;
    private String sl_lm_cell_bank_fraud;
    private String sl_lm_cell_nbank_ca_fraud;
    private String sl_lm_cell_nbank_cf_lost;
    private String sl_lm_cell_nbank_mc_bad;
    private String sl_lm_cell_nbank_cf_fraud;
    private String sl_lm_cell_nbank_other_fraud;
    private String sl_lm_cell_nbank_p2p_refuse;
    private String sl_lm_cell_nbank_com_lost;
    private String sl_lm_cell_nbank_p2p_lost;
    private String sl_lm_cell_nbank_other_lost;
    private String sl_lm_cell_nbank_com_overdue;
    private String sl_lm_cell_bank_refuse;
    private String sl_lm_cell_nbank_p2p_fraud;
    private String sl_lm_cell_bank_lost;
    private String sl_lm_cell_abnormal;
    private String sl_lm_cell_nbank_p2p_overdue;
    private String sl_lm_cell_phone_overdue;
    private String sl_lm_cell_nbank_cf_overdue;
    private String sl_lm_cell_bank_bad;
    private String sl_lm_cell_nbank_mc_refuse;
    private String sl_lm_cell_nbank_ca_lost;
    private String sl_lm_cell_nbank_cf_bad;
    private String sl_lm_cell_nbank_com_bad;
    private String sl_lm_cell_nbank_cf_refuse;
    private String sl_id_nbank_ca_refuse;
    private String sl_id_nbank_com_fraud;
    private String sl_id_p2p_fraud;
    private String sl_id_nbank_ca_bad;
    private String sl_id_bank_overdue;
    private String sl_id_nbank_other_refuse;
    private String sl_id_nbank_mc_fraud;
    private String sl_id_nbank_mc_lost;
    private String sl_id_nbank_other_bad;
    private String sl_id_court_executed;
    private String sl_id_nbank_mc_overdue;
    private String sl_id_nbank_com_refuse;
    private String sl_id_nbank_ca_overdue;
    private String sl_id_nbank_p2p_bad;
    private String sl_id_p2p_lost;
    private String sl_id_p2p_overdue;
    private String sl_id_nbank_other_overdue;
    private String sl_id_bank_fraud;
    private String sl_id_p2p_bad;
    private String sl_id_nbank_ca_fraud;
    private String sl_id_nbank_cf_lost;
    private String sl_id_nbank_mc_bad;
    private String sl_id_nbank_cf_fraud;
    private String sl_id_nbank_other_fraud;
    private String sl_id_nbank_p2p_refuse;
    private String sl_id_nbank_com_lost;
    private String sl_id_nbank_p2p_lost;
    private String sl_id_nbank_other_lost;
    private String sl_id_nbank_com_overdue;
    private String sl_id_bank_refuse;
    private String sl_id_nbank_p2p_fraud;
    private String sl_id_bank_lost;
    private String sl_id_abnormal;
    private String sl_id_nbank_p2p_overdue;
    private String sl_id_phone_overdue;
    private String sl_id_nbank_cf_overdue;
    private String sl_id_bank_bad;
    private String sl_id_nbank_mc_refuse;
    private String sl_id_nbank_ca_lost;
    private String sl_id_nbank_cf_bad;
    private String sl_id_court_bad;
    private String sl_id_nbank_com_bad;
    private String sl_id_nbank_cf_refuse;
    private String sl_id_p2p_refuse;
    private String sl_cell_nbank_ca_refuse;
    private String sl_cell_nbank_com_fraud;
    private String sl_cell_p2p_fraud;
    private String sl_cell_nbank_ca_bad;
    private String sl_cell_bank_overdue;
    private String sl_cell_nbank_other_refuse;
    private String sl_cell_nbank_mc_fraud;
    private String sl_cell_nbank_mc_lost;
    private String sl_cell_nbank_other_bad;
    private String sl_cell_nbank_mc_overdue;
    private String sl_cell_nbank_com_refuse;
    private String sl_cell_nbank_ca_overdue;
    private String sl_cell_nbank_p2p_bad;
    private String sl_cell_p2p_lost;
    private String sl_cell_p2p_overdue;
    private String sl_cell_nbank_other_overdue;
    private String sl_cell_bank_fraud;
    private String sl_cell_p2p_bad;
    private String sl_cell_nbank_ca_fraud;
    private String sl_cell_nbank_cf_lost;
    private String sl_cell_nbank_mc_bad;
    private String sl_cell_nbank_cf_fraud;
    private String sl_cell_nbank_other_fraud;
    private String sl_cell_nbank_p2p_refuse;
    private String sl_cell_nbank_com_lost;
    private String sl_cell_nbank_p2p_lost;
    private String sl_cell_nbank_other_lost;
    private String sl_cell_nbank_com_overdue;
    private String sl_cell_bank_refuse;
    private String sl_cell_nbank_p2p_fraud;
    private String sl_cell_bank_lost;
    private String sl_cell_abnormal;
    private String sl_cell_nbank_p2p_overdue;
    private String sl_cell_phone_overdue;
    private String sl_cell_nbank_cf_overdue;
    private String sl_cell_bank_bad;
    private String sl_cell_nbank_mc_refuse;
    private String sl_cell_nbank_ca_lost;
    private String sl_cell_nbank_cf_bad;
    private String sl_cell_nbank_com_bad;
    private String sl_cell_nbank_cf_refuse;
    private String sl_cell_p2p_refuse;
    private String flag_score;
    private String flag_specialList_c;

}
