
package org.tempuri;

import com.creditinfo.schemas._2012._09.multiconnector.*;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MultiConnectorService", targetNamespace = "http://creditinfo.com/schemas/2012/09/MultiConnector")
@XmlSeeAlso({
    com.creditinfo.schemas._2012._09.multiconnector.messages.response.ObjectFactory.class,
    com.creditinfo.schemas._2012._09.multiconnector.connectors._int.idmstrategy.request.ObjectFactory.class,
    com.creditinfo.schemas._2012._09.multiconnector.ObjectFactory.class,
    com.creditinfo.schemas._2012._09.multiconnector.messages.request.ObjectFactory.class,
    com.creditinfo.schemas._2012._09.multiconnector.connectors._int.idmstrategy.response.ObjectFactory.class,
    com.creditinfo.schemas._2012._09.multiconnector.connectors.ken.idmcb5.company.getcustomreport.request.ObjectFactory.class,
    com.creditinfo.schemas._2012._09.multiconnector.connectors.ken.idmcb5.company.getcustomreport.response.ObjectFactory.class,
    com.creditinfo.schemas._2012._09.multiconnector.connectors.ken.idmcb5.individual.getcustomreport.request.ObjectFactory.class,
    com.creditinfo.schemas._2012._09.multiconnector.connectors.ken.idmcb5.individual.getcustomreport.response.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class
})
public interface MultiConnectorService {


    /**
     * 
     * @param request
     * @return
     *     returns com.creditinfo.schemas._2012._09.multiconnector.MultiConnectorTicket
     * @throws MultiConnectorServiceBeginQueryErrorFaultFaultMessage
     * @throws MultiConnectorServiceBeginQueryUnsupportedSecurityTokenFaultFaultMessage
     * @throws MultiConnectorServiceBeginQueryFailedAuthenticationFaultFaultMessage
     */
    @WebMethod(operationName = "BeginQuery", action = "http://creditinfo.com/schemas/2012/09/MultiConnector/MultiConnectorService/BeginQuery")
    @WebResult(name = "BeginQueryResult", targetNamespace = "http://creditinfo.com/schemas/2012/09/MultiConnector")
    @RequestWrapper(localName = "BeginQuery", targetNamespace = "http://creditinfo.com/schemas/2012/09/MultiConnector", className = "com.creditinfo.schemas._2012._09.multiconnector.BeginQuery")
    @ResponseWrapper(localName = "BeginQueryResponse", targetNamespace = "http://creditinfo.com/schemas/2012/09/MultiConnector", className = "com.creditinfo.schemas._2012._09.multiconnector.BeginQueryResponse")
    public MultiConnectorTicket beginQuery(
            @WebParam(name = "request", targetNamespace = "http://creditinfo.com/schemas/2012/09/MultiConnector")
                    MultiConnectorRequest request)
        throws MultiConnectorServiceBeginQueryErrorFaultFaultMessage, MultiConnectorServiceBeginQueryFailedAuthenticationFaultFaultMessage, MultiConnectorServiceBeginQueryUnsupportedSecurityTokenFaultFaultMessage
    ;

    /**
     * 
     * @param ticket
     * @return
     *     returns com.creditinfo.schemas._2012._09.multiconnector.MultiConnectorResponse
     * @throws MultiConnectorServiceEndQueryFailedAuthenticationFaultFaultMessage
     * @throws MultiConnectorServiceEndQueryInProgressFaultFaultMessage
     * @throws MultiConnectorServiceEndQueryUnsupportedSecurityTokenFaultFaultMessage
     * @throws MultiConnectorServiceEndQueryErrorFaultFaultMessage
     */
    @WebMethod(operationName = "EndQuery", action = "http://creditinfo.com/schemas/2012/09/MultiConnector/MultiConnectorService/EndQuery")
    @WebResult(name = "EndQueryResult", targetNamespace = "http://creditinfo.com/schemas/2012/09/MultiConnector")
    @RequestWrapper(localName = "EndQuery", targetNamespace = "http://creditinfo.com/schemas/2012/09/MultiConnector", className = "com.creditinfo.schemas._2012._09.multiconnector.EndQuery")
    @ResponseWrapper(localName = "EndQueryResponse", targetNamespace = "http://creditinfo.com/schemas/2012/09/MultiConnector", className = "com.creditinfo.schemas._2012._09.multiconnector.EndQueryResponse")
    public MultiConnectorResponse endQuery(
            @WebParam(name = "ticket", targetNamespace = "http://creditinfo.com/schemas/2012/09/MultiConnector")
                    MultiConnectorTicket ticket)
        throws MultiConnectorServiceEndQueryErrorFaultFaultMessage, MultiConnectorServiceEndQueryFailedAuthenticationFaultFaultMessage, MultiConnectorServiceEndQueryInProgressFaultFaultMessage, MultiConnectorServiceEndQueryUnsupportedSecurityTokenFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.creditinfo.schemas._2012._09.multiconnector.MultiConnectorResponse
     * @throws MultiConnectorServiceQueryFailedAuthenticationFaultFaultMessage
     * @throws MultiConnectorServiceQueryTimeoutFaultFaultMessage
     * @throws MultiConnectorServiceQueryErrorFaultFaultMessage
     * @throws MultiConnectorServiceQueryUnsupportedSecurityTokenFaultFaultMessage
     */
    @WebMethod(operationName = "Query", action = "http://creditinfo.com/schemas/2012/09/MultiConnector/MultiConnectorService/Query")
    @WebResult(name = "QueryResult", targetNamespace = "http://creditinfo.com/schemas/2012/09/MultiConnector")
    @RequestWrapper(localName = "Query", targetNamespace = "http://creditinfo.com/schemas/2012/09/MultiConnector", className = "com.creditinfo.schemas._2012._09.multiconnector.Query")
    @ResponseWrapper(localName = "QueryResponse", targetNamespace = "http://creditinfo.com/schemas/2012/09/MultiConnector", className = "com.creditinfo.schemas._2012._09.multiconnector.QueryResponse")
    public MultiConnectorResponse query(
            @WebParam(name = "request", targetNamespace = "http://creditinfo.com/schemas/2012/09/MultiConnector")
                    MultiConnectorRequest request)
        throws MultiConnectorServiceQueryErrorFaultFaultMessage, MultiConnectorServiceQueryFailedAuthenticationFaultFaultMessage, MultiConnectorServiceQueryTimeoutFaultFaultMessage, MultiConnectorServiceQueryUnsupportedSecurityTokenFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.creditinfo.schemas._2012._09.multiconnector.ConnectorSchemaResponse
     * @throws MultiConnectorServiceSchemaErrorFaultFaultMessage
     * @throws MultiConnectorServiceSchemaTimeoutFaultFaultMessage
     * @throws MultiConnectorServiceSchemaUnsupportedSecurityTokenFaultFaultMessage
     * @throws MultiConnectorServiceSchemaFailedAuthenticationFaultFaultMessage
     */
    @WebMethod(operationName = "Schema", action = "http://creditinfo.com/schemas/2012/09/MultiConnector/MultiConnectorService/Schema")
    @WebResult(name = "SchemaResult", targetNamespace = "http://creditinfo.com/schemas/2012/09/MultiConnector")
    @RequestWrapper(localName = "Schema", targetNamespace = "http://creditinfo.com/schemas/2012/09/MultiConnector", className = "com.creditinfo.schemas._2012._09.multiconnector.Schema")
    @ResponseWrapper(localName = "SchemaResponse", targetNamespace = "http://creditinfo.com/schemas/2012/09/MultiConnector", className = "com.creditinfo.schemas._2012._09.multiconnector.SchemaResponse")
    public ConnectorSchemaResponse schema(
            @WebParam(name = "request", targetNamespace = "http://creditinfo.com/schemas/2012/09/MultiConnector")
                    ConnectorSchemaRequest request)
        throws MultiConnectorServiceSchemaErrorFaultFaultMessage, MultiConnectorServiceSchemaFailedAuthenticationFaultFaultMessage, MultiConnectorServiceSchemaTimeoutFaultFaultMessage, MultiConnectorServiceSchemaUnsupportedSecurityTokenFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.creditinfo.schemas._2012._09.multiconnector.ConnectorsListResponse
     * @throws MultiConnectorServiceListConnectorsUnsupportedSecurityTokenFaultFaultMessage
     * @throws MultiConnectorServiceListConnectorsErrorFaultFaultMessage
     * @throws MultiConnectorServiceListConnectorsTimeoutFaultFaultMessage
     * @throws MultiConnectorServiceListConnectorsFailedAuthenticationFaultFaultMessage
     */
    @WebMethod(operationName = "ListConnectors", action = "http://creditinfo.com/schemas/2012/09/MultiConnector/MultiConnectorService/ListConnectors")
    @WebResult(name = "ListConnectorsResult", targetNamespace = "http://creditinfo.com/schemas/2012/09/MultiConnector")
    @RequestWrapper(localName = "ListConnectors", targetNamespace = "http://creditinfo.com/schemas/2012/09/MultiConnector", className = "com.creditinfo.schemas._2012._09.multiconnector.ListConnectors")
    @ResponseWrapper(localName = "ListConnectorsResponse", targetNamespace = "http://creditinfo.com/schemas/2012/09/MultiConnector", className = "com.creditinfo.schemas._2012._09.multiconnector.ListConnectorsResponse")
    public ConnectorsListResponse listConnectors(
            @WebParam(name = "request", targetNamespace = "http://creditinfo.com/schemas/2012/09/MultiConnector")
                    ConnectorsListRequest request)
        throws MultiConnectorServiceListConnectorsErrorFaultFaultMessage, MultiConnectorServiceListConnectorsFailedAuthenticationFaultFaultMessage, MultiConnectorServiceListConnectorsTimeoutFaultFaultMessage, MultiConnectorServiceListConnectorsUnsupportedSecurityTokenFaultFaultMessage
    ;

}
